[package]
name = "downcast-set"
version = "0.0.1"
edition = "2024"
license = "MIT OR Apache-2.0"
publish = false

[features]
default = ["sync"]
sync = ["downcast-rs/sync"]

[dependencies]
downcast-rs = { version = "2.0.1", default-features = false, features = [
    "std",
] }
